#!/bin/bash

# https://gist.github.com/mihow/9c7f559807069a03e302605691f85572
if [ -f .env ]
then
  export $(cat .env | sed 's/#.*//g' | xargs)
fi

: "${BMSURGE_WORKER_GCR_REPOSITORY?Required BMSURGE_WORKER_GCR_REPOSITORY}"

./scripts/build
docker tag bmsurge-renderer "$BMSURGE_WORKER_GCR_REPOSITORY"
docker push "$BMSURGE_WORKER_GCR_REPOSITORY"
