name: bmsurgestreamer

services:
  dj:
    init: true
    tmpfs: /tmp
    image: node:16
    working_dir: /app
    volumes:
      - ./dj:/app
      - ./private/credentials:/credentials:ro
      - ./private/dj/node_modules:/app/node_modules
      - ./private/dj/.yarn:/app/.yarn
      - ./dj/.yarn/releases:/app/.yarn/releases:ro
    env_file:
      - ./private/dj.env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /credentials/bmsurge.service-account.json
    command: bash -c "yarn install && yarn start"
    ports:
      - 127.0.0.1:57263:57263
  icecast:
    image: 'moul/icecast'
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./private/icecast.env
  shouter:
    image: 'dtinth/shouter'
    restart: always
    environment:
      SHOUTER_HOST: icecast
      SHOUTER_PORT: 8000
      SHOUTER_USER: source
      SHOUTER_MOUNT: be-music-surge
      SHOUTER_NAME: Be-Music Surge
      SHOUTER_GENRE: BMS
      SHOUTER_BITRATE: 128
    env_file:
      - ./private/shouter.env
    healthcheck:
      test: 'curl -f https://be-music.spacet.me/radio/ | grep be-music-surge'